FROM        nvidia/cuda:11.3.1-base-ubuntu20.04 
#FROM        debian

ARG         gsd
ENV         GITHUB_STABLE_DIFFUSION $gsd

ARG         branch
ENV         BRANCH $branch

ENV         PIP_EXISTS_ACTION="w"

ENV         DEBIAN_FRONTEND=noninteractive

# TODO: Optimize image size

SHELL       ["/bin/bash", "-c"]

WORKDIR     /
RUN         apt update && apt upgrade -y \
            && apt install -y \
            git \
            libgl1-mesa-glx \
            libglib2.0-0 \
            pip \
            python3 \
            vim \
            less \
            curl \ 
            wget \
            openssh-server \
            && git clone $GITHUB_STABLE_DIFFUSION stable-diffusion \
            && cd stable-diffusion \
            && git checkout $BRANCH

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p $CONDA_DIR

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# SD 
WORKDIR     /stable-diffusion 
RUN         source ~/.bashrc \
            && conda env create -f environment.yml \
            && conda clean -afy

# cleanup APT
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# symlink model
WORKDIR     /stable-diffusion 
            RUN mkdir models/ldm/stable-diffusion-v1 \
            && ln -s "/workspace/sd-v1-4.ckpt" models/ldm/stable-diffusion-v1/model.ckpt

# default script starts an SSH server then sleeps
WORKDIR     /
COPY        start-runpodio.sh .
ENTRYPOINT ["/start-runpodio.sh"]

