FROM        nvidia/cuda:11.3.1-base-ubuntu20.04 
#FROM        debian

ARG         gsd
ENV         GITHUB_STABLE_DIFFUSION $gsd

ARG         branch
ENV         BRANCH $branch

ENV         PIP_EXISTS_ACTION="w"

ENV         DEBIAN_FRONTEND=noninteractive

# TODO: Optimize image size

# make conda work?
SHELL       ["/bin/bash", "-c"]

WORKDIR     /
RUN         apt update && apt upgrade -y \
            && apt install -y \
            git \
            git-lfs \
            libgl1-mesa-glx \
            libglib2.0-0 \
            pip \
            python3 \
            vim \
            less \
            bc \
            curl \ 
            wget \
            openssh-server \
            && git clone $GITHUB_STABLE_DIFFUSION stable-diffusion \
            && cd stable-diffusion \
            && git checkout $BRANCH

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p $CONDA_DIR

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# conda init so that the source ~/.bashrc in the next RUN does the right thing
RUN         conda init bash

# SD, preload models, mega-cmd, jurigged, cleanup APT
WORKDIR     /stable-diffusion 
RUN         source ~/.bashrc \
            && conda install -c conda-forge mamba \
            && ln -s environments-and-requirements/environment-lin-cuda.yml environment.yml \
            && mamba env create -f environment.yml \
            && conda activate invokeai \
            && pip install jurigged \ 
            && pip cache purge \
            && conda clean -afy \
            && python scripts/preload_models.py --no-interactive \
            && wget https://mega.nz/linux/repo/xUbuntu_20.04/amd64/megacmd-xUbuntu_20.04_amd64.deb \
            && apt update \
            && apt install -y ./megacmd-xUbuntu_20.04_amd64.deb \
            && rm megacmd-xUbuntu_20.04_amd64.deb \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*

# default script starts an SSH server then sleeps
WORKDIR     /
COPY        start-runpodio.sh .
ENTRYPOINT ["/start-runpodio.sh"]

