FROM        ghcr.io/damian0815/invoke-ai-runpod:latest

# make conda work?
SHELL       ["/bin/bash", "-c"]

# install jurigged and preload models
WORKDIR     /stable-diffusion 
RUN         source /opt/conda/etc/profile.d/conda.sh \
            && conda activate invokeai \
            && pip install jurigged \ 
            && pip cache purge \
            && python scripts/preload_models.py --no-interactive

# install mega-cmd and then cleanup APT
WORKDIR     /tmp
RUN         wget https://mega.nz/linux/repo/xUbuntu_20.04/amd64/megacmd-xUbuntu_20.04_amd64.deb \
            && apt update \
            && apt install -y ./megacmd-xUbuntu_20.04_amd64.deb \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*


