FROM        ghcr.io/damian0815/invoke-ai-runpod:latest

# make conda work?
SHELL       ["/bin/bash", "-c"]

# preload models and install jurigged
WORKDIR     /stable-diffusion 
RUN         source /opt/conda/etc/profile.d/conda.sh \
            && conda activate invokeai \
            && pip install jurigged \ 
            && pip cache purge \
            && python scripts/preload_models.py 

# install mega-cmd
WORKDIR     /tmp
RUN         wget https://mega.nz/linux/repo/xUbuntu_20.04/amd64/megacmd-xUbuntu_20.04_amd64.deb \
            && apt update && apt install -y ./megacmd-xUbuntu_20.04_amd64.deb

# cleanup APT
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


