name: build-damian0815-dev-docker-image
on: workflow_dispatch
jobs:
  publish-runpodio-docker-image-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the InvokeAI damian0815 main branch Docker image v2
        run: |
              docker build --tag ghcr.io/damian0815/invoke-ai-runpod-2:latest -f docker-build/Dockerfile_runpod_2 docker-build
              docker push ghcr.io/damian0815/invoke-ai-runpod-2:latest
